-   id: validate-sops
    name: Validate SOPS
    description: This hook validates that files are encrypted with SOPS.
    entry: validate-sops
    language: python
    files: '.*secrets.*.(yaml|yml|json|env)$'
